# Generated by Django 4.2.2 on 2023-07-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.response",
            ),
        ),
    ]
